# syntax=docker/dockerfile:1.7

ARG PLAYWRIGHT_VERSION=1.60.0
FROM mcr.microsoft.com/playwright:v${PLAYWRIGHT_VERSION}-noble

WORKDIR /app

ENV CI=1 \
    ASTRO_TELEMETRY_DISABLED=1 \
    PLAYWRIGHT_BROWSERS_PATH=/ms-playwright \
    PLAYWRIGHT_BASE_URL=http://web:8080 \
    LIGHTHOUSE_BASE_URL=http://web:8080

COPY package*.json ./

RUN npm ci \
  && npx playwright --version

COPY . .

CMD ["npm", "run", "qa:phase-5"]